name: Demo

on: push

env:
  MEINE_VARIABLE: Testwert
  REPO_VARIABLE: ${{ vars.REPO_VARIABLE }}

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Variablen ausgeben
        run: |
          echo $MEINE_VARIABLE
          echo $REPO_VARIABLE


      - name: Variable als Output setzen
        id: set_output
        run: |
          echo "wert=$MEINE_VARIABLE" >> $GITHUB_OUTPUT

      - name: Output anzeigen
        run: |
          echo "${{ steps.set_output.outputs.wert }}"
