name: Demo

on: push

env:
  MEINE_VARIABLE: Testwert

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Variable ausgeben
        run: echo $MEINE_VARIABLE

      - name: Variable als Output setzen
        id: set_output
        run: |
          echo "wert=$MEINE_VARIABLE" >> $GITHUB_OUTPUT

      - name: Output anzeigen
        run: |
          echo "${{ steps.set_output.outputs.wert }}"
